export const initialValues = {
	general: {
		name: null,
		date_of_birth: null,
		gender: null,
		current_working_address: {
			institute: null,
			faculty: null,
			department: null,
			lab: null,
			position: null,
		},
		degree_level: null,
		degree_level_year: null,
		academic_rank: null,
		academic_rank_year: null,
		address: null,
		phone: null,
		language_levels: [
			{
				language_name: null,
				listening: null,
				speaking: null,
				writing: null,
				reading: null,
			},
		],
	},
	email: null,
	working_times: [
		{
			start_time: null,
			end_time: null,
			institute: null,
			faculty: null,
			department: null,
			lab: null,
			position: null,
		},
	],
	worked_subjects: [
		{
			name: null,
			subject_code: null,
			supervisor_level: null,
			start_time: null,
			end_time: null,
			acceptance_time: null,
			total_expense: null,
			role: null,
			result: null,
		},
	],
	student_instructions: [
		{
			student_name: null,
			graduate_thesis_name: null,
			graduate_year: null,
			education_level: null,
			product_code: null,
		},
	],
	scientific_work: {
		international_books: [
			{
				name: null,
				subject_code: null,
				publisher: null,
				published_year: null,
				role: null,
				pen_name: null,
			},
		],
		national_books: [
			{
				name: null,
				subject_code: null,
				publisher: null,
				published_year: null,
				role: null,
				pen_name: null,
			},
		],
		international_papers: [
			{
				author: null,
				name: null,
				published_site: null,
				magazine_name: null,
				magazine_number: null,
				published_year: null,
				subject_code: null,
				ISSN: null,
				IF: null,
			},
		],
		national_papers: [
			{
				author: null,
				name: null,
				published_site: null,
				magazine_name: null,
				magazine_number: null,
				published_year: null,
				subject_code: null,
				ISSN: null,
				note: null,
			},
		],
		international_conference_papers: [
			{
				author: null,
				name: null,
				conference_name: null,
				hold_address: null,
				hold_time: null,
				subject_code: null,
				ISBN: null,
				note: null,
			},
		],
		national_conference_papers: [
			{
				author: null,
				name: null,
				conference_name: null,
				hold_address: null,
				hold_time: null,
				subject_code: null,
				ISBN: null,
				note: null,
			},
		],
	},
	other: {
		joined_programs: [
			{
				start_time: null,
				end_time: null,
				name: null,
				role: null,
			},
		],
		joined_conferences: [
			{
				start_time: null,
				end_time: null,
				name: null,
				role: null,
			},
		],
		joined_universities: [
			{
				start_time: null,
				end_time: null,
				name: null,
				activity_detail: null,
			},
		],
	},
	training_process: {
		b: {
			start_time: null,
			end_time: null,
			traning_address: null,
			speciality: null,
			graduate_thesis_name: null,
		},
		m: {
			start_time: null,
			end_time: null,
			traning_address: null,
			speciality: null,
			graduate_thesis_name: null,
		},
		d: {
			start_time: null,
			end_time: null,
			traning_address: null,
			speciality: null,
			graduate_thesis_name: null,
		},
		ds: {
			start_time: null,
			end_time: null,
			traning_address: null,
			speciality: null,
			graduate_thesis_name: null,
		},
	},
}
